# EXERCICES

## NUMPY

In [45]:
import numpy as np

### 1 - Créez un tableau NumPy contenant les entiers de 1 à 10 (inclus).

In [46]:
tableau_entiers = np.arange(1, 11)

tableau_entiers

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### 2 - Créez un tableau NumPy contenant 5 valeurs flottantes générées aléatoirement entre 0 et 1.

In [47]:
tableau_flottants = np.random.rand(5)

tableau_flottants

array([0.86088879, 0.68572808, 0.82912659, 0.18490323, 0.44479109])

### 3 - Créez une fonction qui prend un tableau NumPy en entrée et renvoie la somme de ses éléments.

In [48]:
def somme_tableau(tableau):
    return np.sum(tableau)

resultat_somme_entiers = somme_tableau(tableau_entiers)
resultat_somme_flottants = somme_tableau(tableau_flottants)

print("Somme tableau entiers :", int(resultat_somme_entiers))
print("Somme tableau flottants :", float(resultat_somme_flottants))

Somme tableau entiers : 55
Somme tableau flottants : 3.005437778290555


### 4 - Créez une fonction qui prend deux tableaux NumPy en entrée et renvoie le produit scalaire de ces deux tableaux (dot product).

In [49]:
def produit_scalaire(tableau1, tableau2):
    return np.dot(tableau1, tableau2)

resultat_produit_entiers = produit_scalaire(tableau_entiers, tableau_entiers)
resultat_produit_flottants = produit_scalaire(tableau_flottants, tableau_flottants)

print("Produit scalaire tableau entiers :", resultat_produit_entiers)
print("Produit scalaire tableau flottants :", resultat_produit_flottants)

Produit scalaire tableau entiers : 385
Produit scalaire tableau flottants : 2.130831729231911


### 5 - Créez une fonction qui prend un tableau NumPy en entrée et renvoie un nouveau tableau contenant uniquement les éléments uniques du tableau d'origine.

In [50]:
def elements_uniques(tableau):
    return np.unique(tableau)

tableau = np.array([2, 4, 2, 3, 4, 4, 6])

resultat_uniques = elements_uniques(tableau)

print("Elements uniques :",resultat_uniques)

Elements uniques : [2 3 4 6]


### 6 - Créez une fonction qui prend un tableau NumPy en entrée et renvoie un nouveau tableau contenant les éléments triés par ordre croissant.

In [51]:
def trier_tableau(tableau):
    return np.sort(tableau)

tableau = np.array([8, 4, 8, 6, 9])

resultat_tri = trier_tableau(tableau)

print("Elements triés :", resultat_tri)

Elements triés : [4 6 8 8 9]


### 7 - Créez une fonction qui prend un tableau NumPy en entrée et renvoie la moyenne, la médiane et l'écart type de ses éléments.

In [52]:
def statistiques_tableau(tableau):
    moyenne = np.mean(tableau)
    mediane = np.median(tableau)
    ecart_type = np.std(tableau)
    return moyenne, mediane, ecart_type

stats_entiers = statistiques_tableau(tableau_entiers)
stats_flottants = statistiques_tableau(tableau_flottants)

print(f"Tableau entiers : Moyenne={stats_entiers[0]}, Médiane={stats_entiers[1]}, Écart type={stats_entiers[2]}")
print(f"Tableau flottants : Moyenne={stats_flottants[0]}, Médiane={stats_flottants[1]}, Écart type={stats_flottants[2]}")

Tableau entiers : Moyenne=5.5, Médiane=5.5, Écart type=2.8722813232690143
Tableau flottants : Moyenne=0.601087555658111, Médiane=0.6857280760538121, Écart type=0.25467645411254564


### 8 - Créez une fonction qui prend un tableau NumPy en entrée et renvoie un nouveau tableau où tous les éléments inférieurs à 5 sont remplacés par 0 et tous les éléments supérieurs ou égaux à 5 sont remplacés par 1.

In [53]:
def transformer_tableau(tableau):
    return np.where(tableau < 5, 0, 1)

tableau = np.array([5, 8, 2, 3, 10])
tableau_transform = transformer_tableau(tableau)
print("Elements transformés :", tableau_transform)

Elements transformés : [1 1 0 0 1]


### 9 - Créez une fonction qui prend un tableau NumPy de nombres entiers en entrée et renvoie un nouveau tableau contenant uniquement les nombres premiers du tableau d'origine.

In [54]:
def nombre_premier(n):
    if n <= 1:
        return False
    for i in range(2, n):
        if n % i == 0:
            return False
    return True

tableau_premier = np.array([x for x in tableau_entiers if nombre_premier(x)])
print("Tableau des nombres premiers :", tableau_premier)

Tableau des nombres premiers : [2 3 5 7]


### 10 - Créez un tableau NumPy 2D de taille 3x3 contenant des valeurs entières générées aléatoirement entre 1 et 10.

In [55]:
tableau_2d = np.random.randint(1, 11, size=(3, 3))

print("Tableau en 2D :\n", str(tableau_2d)[1:-1])


Tableau en 2D :
 [ 6  1  5]
 [ 8 10  1]
 [ 8  5  5]
